### ISSUE TITLE
Moving to new org

### ISSUE THREAD

**Issue by cyli** [tryfer/node-tryfer#30]
We are planning on moving this to a new org (as this is not actively being used at Rackspace anymore) and seeking more maintainers, particularly those that actually use this package these days.  :)  Would it be ok if I added you to the admin list, @wadey @suryatech @dustyburwell?  This means you would be able to merge PRs, etc.

You are more qualified than I am to accept PRs anyway.  :)

Also, suggestions for new orgs would be great.  Thanks!  

(cc @Kami)

**Comment by suryatech** [comment]
@cyli Count me in. Thanks :)

**Comment by dustyburwell** [comment]
Of course. Let me run it up the flagpole at work as we may be willing to take this under our org, if you're open to that.

**Comment by wadey** [comment]
Sounds good to me. We are still actively using node-tryfer at Betable (although on an old branch).

**Comment by dustyburwell** [comment]
Out of curiosity, can you elaborate on why rackspace isn't using this anymore?

**Comment by cyli** [comment]
@dustyburwell Thanks lots for offering!  I've just asked at work, and a neutral org is preferred, but would be willing to listen to an argument for another commercial org having it.

And as for why we currently aren't using it anymore, the main project this was written for has been EOLed, and most of our projects are in Python :).  We are looking use it again in the future for another project, which is why we'd still like to have some access to it, but in the interim it seemed more responsible for those who are using it currently to more directly maintain/add to it.  :)

**Comment by Kami** [comment]
@cyli Yeah, new neutral organization works for me.

**Comment by cyli** [comment]
@wadey @dustyburwell Invites should have gone out.  :)  If you haven't gotten them, I think you can just visit https://github.com/tryfer too?
