### ISSUE TITLE
Missing tags 0.2.9 and 0.2.10

### ISSUE THREAD

**Issue by abloom** [tryfer/node-tryfer#32]
Checking the NPM registry I see two versions of `tryfer` that don't have corresponding tags.

```
ᐅ npm info tryfer --registry http://registry.npmjs.org

{ name: 'tryfer',
  description: 'Port of the tryfer Twisted/Python tracing library and Zipkin client',
  'dist-tags': { latest: '0.2.10' },
  versions: [ '0.2.4', '0.2.6', '0.2.7', '0.2.8', '0.2.9', '0.2.10' ],
...
```

Does anyone know the story behind `0.2.9` and `0.2.10`? Would it be possible to publish `0.2.11`? There have been quite a few PRs merged that don't have an official release.

```
* 5cb64b6 - Merge pull request #28 from suryatech/uniqueId (10 weeks ago) <Ying Li>
* f3f1d7e - Merge pull request #26 from niels4/master (4 months ago) <Ying Li>
* 6b7c0c0 - Merge pull request #24 from jorgemsrs/master (4 months ago) <cyli>
* ad480f7 - Merge pull request #25 from suryatech/patch-1 (4 months ago) <cyli>
* d29de74 - Merge pull request #23 from racker/update-npm-on-travis (8 months ago) <cyli>
* 3f879e6 - Merge pull request #22 from dbushong/package-json-node-fix (8 months ago) <cyli>
* 40e6f86 - Merge pull request #20 from wadey/patch-1 (8 months ago) <cyli>
* 994e376 - Merge pull request #19 from racker/microtime (1 year, 7 months ago) <cyli>
```

**Comment by dustyburwell** [comment]
That sounds reasonable. @cyli @suryatech, do you have any context into those missing releases tags? Do either of you have access to publish this to NPM?

**Comment by cyli** [comment]
@abloom @dustyburwell Sorry about that - I think I just forgot to tag when I did the last two.  I can do that and a new release later tonight.

**Comment by cyli** [comment]
[Tags have been added](https://github.com/tryfer/node-tryfer/releases) and the latest version [published to npm](https://www.npmjs.com/package/tryfer).

Thanks for pointing out the missing tags, @abloom!  Closing this for now - please re-open if there are issues with the package!

**Comment by abloom** [comment]
thanks!
