### ISSUE TITLE
getUniqueId generates unsigned longs which overflow in java

### ISSUE THREAD

**Issue by fr0stbyte** [tryfer/node-tryfer#34]
Currently, the getUniqueId function generates too large longs that overflow in java ( which doesn't have support for unsigned longs up until java 8)

From your example in issue #27 
```
> i = randomInt64()
[Int64 value:-Infinity octets:94 54 bb a7 f2 56 dc db]
> i.buffer
<Buffer 94 54 bb a7 f2 56 dc db>
> i.toOctetString()
'9454bba7f256dcdb'
```
Consider this example in scala : 
```
scala> java.lang.Long.parseLong("9454bba7f256dcdb", 16)
java.lang.NumberFormatException: For input string: "9454bba7f256dcdb"
  at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
  at java.lang.Long.parseLong(Long.java:444)
  ... 33 elided
scala> val bi = new java.math.BigInteger("9454bba7f256dcdb", 16)
bi: java.math.BigInteger = 10688374145656741083

scala> bi.longValue
res11: Long = -7758369928052810533
```
You can see that the number is too large to fit into a long which causes the overflow.

Can we change the getUniqueId function so that it uses a lower upper bound for generating the 2 halves of the number ?
PR : https://github.com/tryfer/node-tryfer/pull/33

**Comment by suryatech** [comment]
@fr0stbyte I understand that there seems to an issue with 64 bit numbers.

In what way does this impact the functionality of zipkin?

**Comment by dustyburwell** [comment]
My understanding is that as Zipkin runs on Scala and that generally runs on java7, that this should cause issues. Maybe @fr0stbyte can speak more to the exact issues he's seeing or if they're Zipkin related.

**Comment by fr0stbyte** [comment]
@suryatech 
I guess it is a problem if one needs to access the long representation of ID, which in our case we do as some of the tracing libraries would log the traceid in its long representation. 
Since java < 8 cannot support unsigned ints, I was thinking that it would be great if all the logging will play nice.

**Comment by fr0stbyte** [comment]
@suryatech @dustyburwell 
Just learned that postgresql also doesn't support unsigned longs

**Comment by dustyburwell** [comment]
Seems like a reasonable change. @suryatech do you see any reason not to merge #33 ?

**Comment by suryatech** [comment]
@fr0stbyte Makes sense to have the upper bound. Doesn't hurt to lose some of the trace ids at the top end of the spectrum.

@dustyburwell Nope, maybe @cyli can confirm before merging it.

I don't seem to find the travis-ci report for the commits in #33. Am I missing something ?

**Comment by cyli** [comment]
@suryatech Apologies, I forgot to authorize travis-ci for this organization when it got moved.  A build has run for that PR now, and is green.

I have no objections to this change.  :)  Thanks for checking!  Just out of curiosity (and wanted to make sure), do either of you have merge powers?

**Comment by fr0stbyte** [comment]
@suryatech @cyli @dustyburwell 
Looks like we're all in agreement. Can we get this PR merged in please ?

**Comment by cyli** [comment]
Bumped version to 0.2.12 and pushed to NPM.
