### ISSUE TITLE
Trace.fromRequest in Trace.js fails when using Unix Socket instead of TCP/IP Network Socket

### ISSUE THREAD

**Issue by radkins3141** [tryfer/node-tryfer#36]
In Trace.fromRequest in the file lib/trace.js, a variable called 'host' is unprotected when function call 'request.socket.address()' returns null, resulting in an error later when host.address is dereferenced during the construction of a new Endpoint. This is because, within the request.socket.address function, a native code function called 'getsockname' is undefined on the internally used 'request.socket._handle' object when associated with a Unix Socket.  In contrast, getsockname is properly defined (by node.js) and can be found when the request is associated with a TCP/IP socket. A sample fix for Trace.fromRequest could be to protect the 'host' variable with a slight modification to the current code similar to the following: 

    var hostAddress = null;
    if (request.socket && request.socket.address) {
       hostAddress = request.socket.address();
    }
    // Note hostAddress can be set to null when using a Unix instead of a TCP/IP Socket
    var host =  hostAddress ? hostAddress : {address: '127.0.0.1', port: 80};

[ Please note I'm using node v0.10.26 in an Ubuntu 15.04 environment. Thank's in advance for looking at this issue. ]

**Comment by suryatech** [comment]
@radkins3141 
Thanks for providing context into #31 

#35 is relevant to the above issue. Please have a look at it.

**Comment by radkins3141** [comment]
Hi Surya,

The problem with the work-around for issue #35 seems to be that on line
262, the variable 'host' can still be null. In this case, dereferencing it
to access the 'address' attribute will fail. There are several ways to fix
this, including this simple way:

 var host = (request.socket && request.socket.address ?
     (request.socket.address() ? request.socket.address() : {address:
'127.0.0.1', port: 80})
     : {address: '127.0.0.1', port: 80});

Bob

**Comment by suryatech** [comment]
@radkins3141 
In the case of a Unix socket, is request.socket.address `undefined` or does it return `null` ?
If the latter is true, your case makes perfect sense and we should make changes to address it.

**Comment by radkins3141** [comment]
on Linux -- at least on node v0.10.26 and Ubuntu 15.04 --
'request.socket.address' does return null when using a unix socket
